// Code generated by protoc-gen-go. DO NOT EDIT.
// source: extend.proto

package codegen

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptorpb "google.golang.org/protobuf/types/descriptorpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Genmsg struct {
	If2                  int32    `protobuf:"varint,1,opt,name=if2,proto3" json:"if2,omitempty"`
	F2                   string   `protobuf:"bytes,2,opt,name=f2,proto3" json:"f2,omitempty"`
	F3                   bool     `protobuf:"varint,3,opt,name=f3,proto3" json:"f3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genmsg) Reset()         { *m = Genmsg{} }
func (m *Genmsg) String() string { return proto.CompactTextString(m) }
func (*Genmsg) ProtoMessage()    {}
func (*Genmsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_extend_93dcc31159ece336, []int{0}
}
func (m *Genmsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genmsg.Unmarshal(m, b)
}
func (m *Genmsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genmsg.Marshal(b, m, deterministic)
}
func (dst *Genmsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genmsg.Merge(dst, src)
}
func (m *Genmsg) XXX_Size() int {
	return xxx_messageInfo_Genmsg.Size(m)
}
func (m *Genmsg) XXX_DiscardUnknown() {
	xxx_messageInfo_Genmsg.DiscardUnknown(m)
}

var xxx_messageInfo_Genmsg proto.InternalMessageInfo

func (m *Genmsg) GetIf2() int32 {
	if m != nil {
		return m.If2
	}
	return 0
}

func (m *Genmsg) GetF2() string {
	if m != nil {
		return m.F2
	}
	return ""
}

func (m *Genmsg) GetF3() bool {
	if m != nil {
		return m.F3
	}
	return false
}

var E_ExtendFile = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FileOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_file",
	Tag:           "varint,20000,opt,name=extend_file,json=extendFile",
	Filename:      "extend.proto",
}

var E_ExtendService = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_service",
	Tag:           "varint,20000,opt,name=extend_service,json=extendService",
	Filename:      "extend.proto",
}

var E_ExtendMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_method",
	Tag:           "varint,20000,opt,name=extend_method,json=extendMethod",
	Filename:      "extend.proto",
}

var E_ExtendEnum = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.EnumOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_enum",
	Tag:           "varint,20000,opt,name=extend_enum,json=extendEnum",
	Filename:      "extend.proto",
}

var E_ExtendEnumValue = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_enum_value",
	Tag:           "varint,20000,opt,name=extend_enum_value,json=extendEnumValue",
	Filename:      "extend.proto",
}

var E_Myself = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         50000,
	Name:          "codegen.myself",
	Tag:           "varint,50000,opt,name=myself",
	Filename:      "extend.proto",
}

var E_Skdfj = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*int32)(nil),
	Field:         50002,
	Name:          "codegen.skdfj",
	Tag:           "varint,50002,opt,name=skdfj",
	Filename:      "extend.proto",
}

var E_Kad = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         50003,
	Name:          "codegen.kad",
	Tag:           "bytes,50003,opt,name=kad",
	Filename:      "extend.proto",
}

var E_Cfg = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MessageOptions)(nil),
	ExtensionType: (*Genmsg)(nil),
	Field:         50004,
	Name:          "codegen.cfg",
	Tag:           "bytes,50004,opt,name=cfg",
	Filename:      "extend.proto",
}

var E_ExtendField = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         20000,
	Name:          "codegen.extend_field",
	Tag:           "varint,20000,opt,name=extend_field,json=extendField",
	Filename:      "extend.proto",
}

func init() {
	proto.RegisterType((*Genmsg)(nil), "codegen.genmsg")
	proto.RegisterExtension(E_ExtendFile)
	proto.RegisterExtension(E_ExtendService)
	proto.RegisterExtension(E_ExtendMethod)
	proto.RegisterExtension(E_ExtendEnum)
	proto.RegisterExtension(E_ExtendEnumValue)
	proto.RegisterExtension(E_Myself)
	proto.RegisterExtension(E_Skdfj)
	proto.RegisterExtension(E_Kad)
	proto.RegisterExtension(E_Cfg)
	proto.RegisterExtension(E_ExtendField)
}

func init() { proto.RegisterFile("extend.proto", fileDescriptor_extend_93dcc31159ece336) }

var fileDescriptor_extend_93dcc31159ece336 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0x87, 0x49, 0x42, 0x7b, 0x6f, 0xa7, 0xda, 0xea, 0xac, 0x82, 0xf8, 0x27, 0xba, 0xea, 0x2a,
	0x85, 0x66, 0x21, 0xce, 0x46, 0x10, 0x2b, 0x6e, 0x4a, 0x21, 0x82, 0xdb, 0xd0, 0x66, 0xce, 0xc4,
	0xd8, 0x49, 0xa6, 0x64, 0x92, 0xa2, 0x2f, 0xe0, 0x53, 0xb8, 0xf0, 0x91, 0x44, 0x7d, 0x20, 0xc9,
	0x4c, 0xaa, 0xa5, 0x8d, 0x74, 0x97, 0xcc, 0xef, 0x7c, 0xdf, 0xe1, 0xcc, 0x1c, 0xb4, 0x03, 0x4f,
	0x39, 0xa4, 0xd4, 0x9d, 0x67, 0x22, 0x17, 0xf8, 0x5f, 0x28, 0x28, 0x44, 0x90, 0x1e, 0x38, 0x91,
	0x10, 0x11, 0x87, 0xbe, 0x3a, 0x9e, 0x16, 0xac, 0x4f, 0x41, 0x86, 0x59, 0x3c, 0xcf, 0x45, 0xa6,
	0x4b, 0xcf, 0x08, 0x6a, 0x46, 0x90, 0x26, 0x32, 0xc2, 0x7b, 0xc8, 0x8a, 0xd9, 0xc0, 0x36, 0x1c,
	0xa3, 0xd7, 0xf0, 0xcb, 0x4f, 0xdc, 0x41, 0x26, 0x1b, 0xd8, 0xa6, 0x63, 0xf4, 0x5a, 0xbe, 0x59,
	0xfd, 0x7b, 0xb6, 0xe5, 0x18, 0xbd, 0xff, 0xbe, 0xc9, 0x3c, 0x72, 0x89, 0xda, 0xba, 0x6d, 0xc0,
	0x62, 0x0e, 0xf8, 0xd0, 0xd5, 0xdd, 0xdc, 0x65, 0x37, 0xf7, 0x26, 0xe6, 0x30, 0x9e, 0xe7, 0xb1,
	0x48, 0xa5, 0xfd, 0xf6, 0x6a, 0x28, 0x10, 0x69, 0xa4, 0x8c, 0xc8, 0x2d, 0xea, 0x54, 0x02, 0x09,
	0xd9, 0x22, 0x0e, 0x01, 0x9f, 0x6c, 0x38, 0xee, 0x74, 0xb2, 0xae, 0xd9, 0xd5, 0x60, 0x95, 0x92,
	0x21, 0xaa, 0x0e, 0x82, 0x04, 0xf2, 0x07, 0x41, 0xf1, 0xf1, 0x86, 0x68, 0xa4, 0x82, 0x75, 0x4f,
	0x75, 0x71, 0x3a, 0x5c, 0x99, 0x08, 0xd2, 0x22, 0xa9, 0x99, 0x68, 0x98, 0x16, 0xc9, 0x1f, 0x13,
	0x95, 0x11, 0x19, 0xa3, 0xfd, 0x15, 0x41, 0xb0, 0x98, 0xf0, 0x02, 0xf0, 0x69, 0xad, 0xe6, 0xbe,
	0xcc, 0xd6, 0x5d, 0xdd, 0x5f, 0x97, 0xca, 0xc9, 0x05, 0x6a, 0x26, 0xcf, 0x12, 0x38, 0xab, 0xb9,
	0x9a, 0x11, 0x48, 0x39, 0x89, 0x7e, 0x1c, 0xef, 0x2f, 0xfa, 0x69, 0x2a, 0x80, 0x9c, 0xa3, 0x86,
	0x9c, 0x51, 0xf6, 0xb8, 0x9d, 0xfc, 0x50, 0x64, 0xc3, 0xd7, 0xf5, 0xc4, 0x43, 0xd6, 0x6c, 0x42,
	0xb7, 0x63, 0x9f, 0x0a, 0x6b, 0xf9, 0x65, 0x35, 0xb9, 0x46, 0x56, 0xc8, 0xa2, 0xed, 0xd0, 0x97,
	0x82, 0xda, 0x83, 0xae, 0x5b, 0x2d, 0xa9, 0xab, 0xf7, 0xcf, 0x2f, 0x71, 0x72, 0xb5, 0xdc, 0xe4,
	0x80, 0xc5, 0xc0, 0x29, 0x3e, 0xaa, 0xd9, 0x29, 0xe0, 0x1b, 0xaf, 0xd8, 0x5e, 0x2e, 0x15, 0x70,
	0x3a, 0x6d, 0xaa, 0x5a, 0xef, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x63, 0x26, 0x83, 0x82, 0x14, 0x03,
	0x00, 0x00,
}
